name: gitee

on:
  schedule:
    - cron: '* 10 * * 6'
  push:
      branches:
        - main

jobs:
  user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - github: xiexianbin
            gitee: xiexianbin
    steps:
      - name: Cache src repo
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ github.workspace }}/git-mirrors-cache
          key: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-${{ steps.info.outputs.time }}
          restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-

      - name: User xiexianbin mirror
        uses: x-actions/git-mirrors@v0.2.4
        with:
          src: github/${{ matrix.github }}
          src_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          dst: gitee/${{ matrix.gitee }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          black_list: "openbilibili"
          clone_style: ssh

      - name: Print cache path
        run: |
          dir="${{ github.workspace }}/git-mirrors-cache"
          if [ -d "${dir}" ]; then
            tree -L 2 ${dir}
          else
            echo "empty"
          fi

  orgs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - github: kbcx
            gitee: kb-cx
          - github: godeepl
            gitee: godeepl
          - github: openlava
            gitee: openlava
          - github: OpenRDF
            gitee: OpenRDF
          - github: x-actions
            gitee: x-actions
          - github: x-mirrors
            gitee: x-mirrors
          - github: yaochi
            gitee: yaochi-mirrors
          - github: x-ca
            gitee: x-ca
    steps:
      - name: Cache src repo
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ github.workspace }}/git-mirrors-cache
          key: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-${{ steps.info.outputs.time }}
          restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-

      - name: Organization ${{ matrix.github }} mirror
        uses: x-actions/git-mirrors@v0.2.4
        with:
          src: github/${{ matrix.github }}
          src_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          dst: gitee/${{ matrix.gitee }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          clone_style: ssh

      - name: Print cache path
        run: |
          dir="${{ github.workspace }}/git-mirrors-cache"
          if [ -d "${dir}" ]; then
            tree -L 2 ${dir}
          else
            echo "empty"
          fi
