name: gitee

on:
  schedule:
    - cron: '* 10 * * 6'
  push:
      branches:
        - main

jobs:
  github-to-gitee:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - github: kbcx
            gitee: kbcx
    steps:

      - name: Cache src repo
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ github.workspace }}/hub-mirror-cache
          key: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-${{ steps.info.outputs.time }}
          restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-

      - name: User xiexianbin mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/xiexianbin
          dst: gitee/xiexianbin
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user

      - name: Organization ${{ matrix.github }} mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ matrix.github }}
          dst: gitee/${{ matrix.gitee }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org

      - name: Print cache path
        run: |
          ls -la ${{ github.workspace }}/hub-mirror-cache
