name: gitee

on:
  schedule:
    - cron: '* 10 * * 6'
  push:
      branches:
        - main

jobs:
  github-to-gitee:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - github: xiexianbin
            gitee: xiexianbin
          - github: kbcx
            gitee: kbcx
    steps:
      - name: Organization mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ matrix.github }}
          dst: gitee/${{ matrix.gitee }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
